# shell

Run python from the shell.

`>>> which python`

`>>> python`

`>>> quit()`

# modules

In [1]:
import mymodule

print(mymodule.favcolor)

mymodule.sayhi("Tester")

v = mymodule.vec3(1, 2, 3)
print(v)

green
Hi, Tester
(1, 2, 3)


Now add a new variable favshape to mymodule.

In [2]:
import mymodule

print(mymodule.favshape)

AttributeError: module 'mymodule' has no attribute 'favshape'

Q: Why did we get an error since we imported our updated module again?

A: A modules is only imported once the first time. To reimport it we'll need to restart the kernel. Try it.

Modules can themselves import other modules.

In [3]:
import myothermodule

print(mymodule.favcolor)
print(myothermodule.favcolor)

green
light-green


In [4]:
import xyz

In [5]:
print(xyz.x, xyz.y, xyz.z)

1 2 3


Open a shell, and run `python xyz.py` from within the same directory.

# PEP 8 style guide

e.g., see this [PEP 8 cheatsheet](https://gist.github.com/RichardBronosky/454964087739a449da04) or this [explanation of PEP 8](https://realpython.com/python-pep8/) among many others...

# list comprehensions

### *values* = [ *expression* **for** *value* **in** *collection* ]

[one of many websites on list comprehensions](https://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/)

[associated YouTube video with above URL](https://www.youtube.com/watch?v=5_cJIcgM7rw&feature=youtu.be&t=52s)

In [4]:
[x for x in range(5)]

[0, 1, 2, 3, 4]

In [5]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [6]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [9]:
def cubeit(value):
    return value**3

[cubeit(x) for x in range(5)]

[0, 1, 8, 27, 64]

In [12]:
# list comprehensions replace for loops in a nice easy to read (usually) format
values = []
for x in range(5):
    values.append(cubeit(x))

print(values)

[0, 1, 8, 27, 64]


In [35]:
[word.lower() for word in ['Alligator', 'MonKey', 'Elephant']]

['alligator', 'monkey', 'elephant']

In [121]:
['even' if x % 2 == 0 else 'odd'
 for x in range(5)
]

['even', 'odd', 'even', 'odd', 'even']

### *values* = [ *expression* **for** *value* **in** *collection* **if** *condition* ]

In [7]:
[i for i in range(5) if 1 <= i <= 3]

[1, 2, 3]

In [8]:
[j for j in range(5) if j % 2 == 0]

[0, 2, 4]

In [11]:
# list comprehensions replace for loops in a nice easy to read (usually) format
values = []
for i in range(5):
    if 1 <= i <= 3:
        values.append(i)

print(values)

[0, 1, 2, 3, 4]


### values can be collections themselves (e.g. lists or tuples, etc.)

In [27]:
[item for item in enumerate(range(5))]

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

In [29]:
[(index+1, value**2) for (index, value) in enumerate(range(5))]

[(1, 0), (2, 1), (3, 4), (4, 9), (5, 16)]

In [26]:
[index for (index, value) in enumerate(range(5)) if value % 2 == 0]

[0, 2, 4]

### dictionary comprehensions { key: value for ... }

In [32]:
{
    index + 1: value**2
    for (index, value) in  enumerate(range(5))
}

{1: 0, 2: 1, 3: 4, 4: 9, 5: 16}

### nested loops

### *values* = [ *expression(value)* **for** *subcollection* **in** *collection* **for** *value* **in** *subcollection* ]

In [15]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


In [22]:
[item**2 for row in matrix for item in row]

[1, 4, 9, 16]

In [23]:
[item**2 for row in matrix for item in row if np.sum(row) > 3]

[9, 16]

In [24]:
# list comprehensions replace for loops in a nice easy to read (usually) format
values = []
for i in range(matrix.shape[0]):
    row = matrix[i, :]
    if np.sum(row) > 3:
        for item in row:
            values.append(item**2)

print(values)

[9, 16]


In [25]:
[item**2
 for row in matrix
 for item in row
 if np.sum(row) > 3]

[9, 16]

### List Comprehension Exercise: Find all odd values in [0, 100] that are divisible by 3.

### List Comprehension Exercise: Flatten a 4x4 random matrix into a one dimensional 16-element list.

### NumPy Exercise: Reshape the 16-element list from above into a 8x2 matrix.

### List Comprehension Exercise: Make a list with the square root of each odd number in [10, 11, 12, 13, 14, 15].

### List Comprehension Exercise: Make a list of the first letters of each of the words in ["Alligator", "Monkey", "Elephant"].

# generators

* grab items only as needed (don't create all the values at once, just one at a time)
* once grabbed, value is used up (can only loop over the values once)

In [38]:
values = (i for i in range(5))  # !!! -> use () instead of []

print(values)
print(list(values))
print(list(values))

<generator object <genexpr> at 0x10e4e9e58>
[0, 1, 2, 3, 4]
[]


In [41]:
values = (i for i in range(5))

print(next(values))
print(next(values))
print(next(values))
print(next(values))
print(next(values))
print(next(values))  # ERROR, nothing left to generate

0
1
2
3
4


StopIteration: 

In [44]:
# can pass generators as function arguments
sum(i**2 for i in range(5) if i < 3)

5

In [54]:
from sklearn import datasets

diabetes = datasets.load_diabetes()
X = diabetes.data[:10, :]
y = diabetes.target[:10]

In [56]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)

gen = kf.split(X, y)

print(gen)
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))

<generator object _BaseKFold.split at 0x1a1d8e3ed0>
(array([0, 2, 3, 4, 5, 6, 7, 9]), array([1, 8]))
(array([1, 2, 3, 4, 6, 7, 8, 9]), array([0, 5]))
(array([0, 1, 3, 4, 5, 6, 8, 9]), array([2, 7]))
(array([0, 1, 2, 3, 5, 6, 7, 8]), array([4, 9]))
(array([0, 1, 2, 4, 5, 7, 8, 9]), array([3, 6]))


StopIteration: 

In [57]:
gen = kf.split(X, y)

for train_idx, test_idx in gen:
    print(train_idx, test_idx)

[0 2 3 4 5 6 7 9] [1 8]
[1 2 3 4 6 7 8 9] [0 5]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 4 5 7 8 9] [3 6]


In [58]:
for train_idx, test_idx in kf.split(X, y):
    print(train_idx, test_idx)

[0 2 3 4 5 6 7 9] [1 8]
[1 2 3 4 6 7 8 9] [0 5]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 4 5 7 8 9] [3 6]


# zip

In [80]:
a = zip([0, 1, 2, 3, 4], ['zero', 'one', 'two', 'three', 'four'])
print(a)
print(list(a))

[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]


In [81]:
print(list(a))

[]


In [83]:
# zip returns a generator!
a = zip([0, 1, 2, 3, 4], ['zero', 'one', 'two', 'three', 'four'])
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))
print(next(a))

(0, 'zero')
(1, 'one')
(2, 'two')
(3, 'three')
(4, 'four')


StopIteration: 

In [84]:
a = zip([0, 1, 2, 3, 4], ['zero', 'one', 'two', 'three', 'four'], 'abcde')
print(list(a))

[(0, 'zero', 'a'), (1, 'one', 'b'), (2, 'two', 'c'), (3, 'three', 'd'), (4, 'four', 'e')]


In [85]:
a = zip([0, 1, 2, 3, 4], ['zero', 'one', 'two', 'three', 'four'], 'abcd')
print(list(a))

[(0, 'zero', 'a'), (1, 'one', 'b'), (2, 'two', 'c'), (3, 'three', 'd')]


In [86]:
a = zip([0, 1, 2, 3, 4], ['zero', 'one', 'two', 'three', 'four'], 'abcde', 5)
print(list(a))

TypeError: zip argument #4 must support iteration

In [87]:
# unzipping!

numbers = [0, 1, 2, 3, 4]
words = ['zero', 'one', 'two', 'three', 'four']

a = zip(numbers, words)

n, w = zip(*a)

print(n)
print(w)

(0, 1, 2, 3, 4)
('zero', 'one', 'two', 'three', 'four')


In [97]:
a = [1, 2, 3]
b = [10, 20, 30]

[x + y for x, y in zip(a, b)]

[11, 22, 33]

# unpacking

In [89]:
a, b, c, d, e = [0, 1, 2, 3, 4]

print(a, b, c, d, e)

0 1 2 3 4


In [93]:
a, b, c, d, e = [0, 1, 2, 3]

ValueError: not enough values to unpack (expected 5, got 4)

In [94]:
a, b, c, d = [0, 1, 2, 3, 4]

ValueError: too many values to unpack (expected 4)

# lambdas

### lambda arguments : expression

In [100]:
def add(a, b):
    return a + b

add(2, 3)

5

In [102]:
add2 = lambda a, b : a + b

add2(2, 3)

5

In [104]:
a = map(lambda x : x**2, [1, 2, 3, 4])

list(a)

[1, 4, 9, 16]

# Numba

### Just-in-time (JIT) compiler for speeding up python code

In [ ]:
def bubblesort(X):
    N = len(X)
    for end in range(N, 1, -1):
        for i in range(end - 1):
            cur = X[i]
            if cur > X[i + 1]:
                tmp = X[i]
                X[i] = X[i + 1]
                X[i + 1] = tmp

In [107]:
inorder = np.arange(0.0, 10.0, 0.01)

shuffled = inorder.copy()                         
np.random.shuffle(shuffled)

bubblesorted = shuffled.copy()
bubblesort(bubblesorted)

print(np.array_equal(bubblesorted, inorder))

True


In [108]:
%timeit bubblesorted[:] = shuffled[:]; bubblesort(bubblesorted)

169 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [109]:
from numba import autojit

bubblesort_numba = autojit(bubblesort)

In [110]:
%timeit bubblesorted[:] = shuffled[:]; bubblesort_numba(bubblesorted)

478 µs ± 6.53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [117]:
# This kind of quadruply-nested for-loop is going to be quite slow.
# Using Numba we can compile this code to LLVM which then gets
# compiled to machine code

def filter2d(image, filt):
    M, N = image.shape
    Mf, Nf = filt.shape
    Mf2 = Mf // 2
    Nf2 = Nf // 2
    result = np.zeros_like(image)
    for i in range(Mf2, M - Mf2):
        for j in range(Nf2, N - Nf2):
            num = 0.0
            for ii in range(Mf):
                for jj in range(Nf):
                    num += (filt[Mf-1-ii, Nf-1-jj] * image[i-Mf2+ii, j-Nf2+jj])
            result[i, j] = num
    return result

filter2d_numba = autojit(filter2d)

In [118]:
# Now filter2d_numba runs at speeds as if you had first translated
# it to C, compiled the code and wrapped it with Python
image = np.random.random((100, 100))
filt = np.random.random((10, 10))

In [119]:
%timeit res = filter2d(image, filt)

382 ms ± 5.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [120]:
%timeit res = filter2d_numba(image, filt)

766 µs ± 2.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


And some more examples at http://numba.pydata.org/numba-doc/0.15.1/examples.html